# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 01:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields
import walltv.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Panel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('columns', models.PositiveSmallIntegerField(help_text='Columnas en una fila no deberían exceder 12', verbose_name='Columnas')),
            ],
            options={
                'ordering': ('order',),
                'verbose_name': 'Panel',
                'verbose_name_plural': 'Panels',
                'abstract': False,
            },
            bases=(walltv.models.ModelRenderMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Row',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('height', models.PositiveSmallIntegerField(help_text='Porcentage usado verticalmente de la pantalla')),
            ],
            options={
                'ordering': ('order',),
                'verbose_name': 'Row',
                'verbose_name_plural': 'Rows',
                'abstract': False,
            },
            bases=(walltv.models.ModelRenderMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CarouselPanel',
            fields=[
                ('panel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='walltv.Panel')),
                ('wait_time', models.PositiveSmallIntegerField(verbose_name='Tiempo de espera')),
            ],
            options={
                'verbose_name': 'Carousel panel',
                'verbose_name_plural': 'Carousel panels',
                'abstract': False,
            },
            bases=('walltv.panel',),
        ),
        migrations.CreateModel(
            name='ImageForCarouselField',
            fields=[
                ('panel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='walltv.Panel')),
                ('image_file', models.ImageField(upload_to='', verbose_name='Image file')),
                ('carousel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='walltv.CarouselPanel')),
            ],
            options={
                'verbose_name': 'Image for carousel',
                'verbose_name_plural': 'Images for carousel',
                'abstract': False,
            },
            bases=('walltv.panel',),
        ),
        migrations.CreateModel(
            name='ImagePanel',
            fields=[
                ('panel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='walltv.Panel')),
                ('image', models.ImageField(upload_to='', verbose_name='Imagen')),
            ],
            options={
                'verbose_name': 'URL video panel',
                'verbose_name_plural': 'URL video panels',
                'abstract': False,
            },
            bases=('walltv.panel',),
        ),
        migrations.CreateModel(
            name='RSSPanel',
            fields=[
                ('panel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='walltv.Panel')),
                ('url', models.URLField(verbose_name='URL')),
            ],
            options={
                'verbose_name': 'RSS panel',
                'verbose_name_plural': 'RSS panels',
                'abstract': False,
            },
            bases=('walltv.panel',),
        ),
        migrations.CreateModel(
            name='TextPanel',
            fields=[
                ('panel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='walltv.Panel')),
                ('text', models.TextField(verbose_name='Texto')),
            ],
            options={
                'verbose_name': 'Text panel',
                'verbose_name_plural': 'Text panels',
                'abstract': False,
            },
            bases=('walltv.panel',),
        ),
        migrations.CreateModel(
            name='URLVideoPanel',
            fields=[
                ('panel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='walltv.Panel')),
                ('video_url', embed_video.fields.EmbedVideoField(verbose_name='URL del video')),
            ],
            options={
                'verbose_name': 'URL video panel',
                'verbose_name_plural': 'URL video panels',
                'abstract': False,
            },
            bases=('walltv.panel',),
        ),
        migrations.CreateModel(
            name='VideoPanel',
            fields=[
                ('panel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='walltv.Panel')),
                ('file', models.FileField(upload_to='', verbose_name='Archivo')),
            ],
            options={
                'verbose_name': 'Video panel',
                'verbose_name_plural': 'Video panels',
                'abstract': False,
            },
            bases=('walltv.panel',),
        ),
        migrations.CreateModel(
            name='WeatherPanel',
            fields=[
                ('panel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='walltv.Panel')),
                ('location', models.CharField(max_length=255, verbose_name='Ubicación')),
            ],
            options={
                'verbose_name': 'Weather panel',
                'verbose_name_plural': 'Weather panels',
                'abstract': False,
            },
            bases=('walltv.panel',),
        ),
        migrations.AddField(
            model_name='panel',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panels', to='walltv.Row', verbose_name='Padre'),
        ),
        migrations.AddField(
            model_name='panel',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_walltv.panel_set+', to='contenttypes.ContentType'),
        ),
    ]
