# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 01:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields
import walltv.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageForImagesField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='Panel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('columns', models.PositiveSmallIntegerField(help_text="Columns in a row shouldn't exceed 12", verbose_name='Columns')),
            ],
            options={
                'abstract': False,
            },
            bases=(walltv.models.ModelRenderMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Row',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('height', models.PositiveSmallIntegerField(help_text='Percentage used vertically of the screen')),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
            bases=(walltv.models.ModelRenderMixin, models.Model),
        ),
        migrations.CreateModel(
            name='RSSPanel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='URL')),
            ],
        ),
        migrations.CreateModel(
            name='TextPanel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Text')),
            ],
        ),
        migrations.CreateModel(
            name='WeatherPanel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255, verbose_name='Location')),
            ],
        ),
        migrations.CreateModel(
            name='CarouselPanel',
            fields=[
                ('panel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='walltv.Panel')),
                ('wait_time', models.PositiveSmallIntegerField(verbose_name='Wait time')),
            ],
            options={
                'abstract': False,
            },
            bases=('walltv.panel',),
        ),
        migrations.CreateModel(
            name='ImagePanel',
            fields=[
                ('panel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='walltv.Panel')),
                ('image', models.ImageField(upload_to='', verbose_name='Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('walltv.panel',),
        ),
        migrations.CreateModel(
            name='URLVideoPanel',
            fields=[
                ('panel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='walltv.Panel')),
                ('video_url', embed_video.fields.EmbedVideoField(verbose_name='Video URL')),
            ],
            options={
                'abstract': False,
            },
            bases=('walltv.panel',),
        ),
        migrations.CreateModel(
            name='VideoPanel',
            fields=[
                ('panel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='walltv.Panel')),
                ('file', models.FileField(upload_to='', verbose_name='File')),
            ],
            options={
                'abstract': False,
            },
            bases=('walltv.panel',),
        ),
        migrations.AddField(
            model_name='panel',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panels', to='walltv.Row', verbose_name='Parent'),
        ),
        migrations.AddField(
            model_name='panel',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_kiosktv.panel_set+', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='imageforimagesfield',
            name='carousel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='walltv.CarouselPanel'),
        ),
    ]
