# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 02:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walltv', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carouselpanel',
            options={'verbose_name': 'Panel de carrusel de imágenes', 'verbose_name_plural': 'Paneles de carrusel de imágenes'},
        ),
        migrations.AlterModelOptions(
            name='imageforcarouselfield',
            options={'verbose_name': 'Imagen para carrusel', 'verbose_name_plural': 'Imagenes para carrusel'},
        ),
        migrations.AlterModelOptions(
            name='imagepanel',
            options={'verbose_name': 'Panel de imagen', 'verbose_name_plural': 'Paneles de imagen'},
        ),
        migrations.AlterModelOptions(
            name='panel',
            options={'ordering': ('order',), 'verbose_name': 'Panel', 'verbose_name_plural': 'Paneles'},
        ),
        migrations.AlterModelOptions(
            name='row',
            options={'ordering': ('order',), 'verbose_name': 'Fila', 'verbose_name_plural': 'Filas'},
        ),
        migrations.AlterModelOptions(
            name='rsspanel',
            options={'verbose_name': 'Panel de RSS', 'verbose_name_plural': 'Paneles de RSS'},
        ),
        migrations.AlterModelOptions(
            name='textpanel',
            options={'verbose_name': 'Panel de texto', 'verbose_name_plural': 'Paneles de texto'},
        ),
        migrations.AlterModelOptions(
            name='urlvideopanel',
            options={'verbose_name': 'Panel de video con URL', 'verbose_name_plural': 'Paneles de video con URL'},
        ),
        migrations.AlterModelOptions(
            name='videopanel',
            options={'verbose_name': 'Panel de video', 'verbose_name_plural': 'Paneles de video'},
        ),
        migrations.AlterModelOptions(
            name='weatherpanel',
            options={'verbose_name': 'Panel de tiempo', 'verbose_name_plural': 'Paneles de tiempo'},
        ),
        migrations.AlterField(
            model_name='imageforcarouselfield',
            name='image_file',
            field=models.ImageField(upload_to='', verbose_name='Archivo de imagen'),
        ),
    ]
