# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 02:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields
import kiosktv.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False)),
                ('name', models.CharField(max_length=255)),
                ('columns', models.PositiveSmallIntegerField(help_text="Columns in a row shouldn't exceed 12")),
            ],
            options={
                'abstract': False,
            },
            bases=(kiosktv.models.ModelRenderMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ImageForImagesField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Row',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False)),
                ('name', models.CharField(max_length=255)),
                ('height', models.PositiveSmallIntegerField(help_text='Percentage used vertically of the screen')),
            ],
            options={
                'abstract': False,
                'ordering': ('order',),
            },
            bases=(kiosktv.models.ModelRenderMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CarouselFrame',
            fields=[
                ('frame_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kiosktv.Frame')),
                ('wait_time', models.PositiveSmallIntegerField()),
            ],
            options={
                'abstract': False,
            },
            bases=('kiosktv.frame',),
        ),
        migrations.CreateModel(
            name='URLVideoFrame',
            fields=[
                ('frame_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kiosktv.Frame')),
                ('video_url', embed_video.fields.EmbedVideoField()),
            ],
            options={
                'abstract': False,
            },
            bases=('kiosktv.frame',),
        ),
        migrations.CreateModel(
            name='VideoFrame',
            fields=[
                ('frame_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kiosktv.Frame')),
                ('file', models.FileField(upload_to='')),
            ],
            options={
                'abstract': False,
            },
            bases=('kiosktv.frame',),
        ),
        migrations.AddField(
            model_name='frame',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kiosktv.Row'),
        ),
        migrations.AddField(
            model_name='frame',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_kiosktv.frame_set+', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='imageforimagesfield',
            name='carousel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kiosktv.CarouselFrame'),
        ),
    ]
