# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 00:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kiosktv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselFrame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('columns', models.PositiveSmallIntegerField(help_text='Columns in a row cannot exceed 12')),
                ('wait_time', models.PositiveSmallIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImageForImagesField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('carousel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kiosktv.CarouselFrame')),
            ],
        ),
        migrations.CreateModel(
            name='Row',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.PositiveSmallIntegerField(choices=[('5', 5), ('10', 10), ('15', 15), ('20', 20), ('25', 25), ('30', 30), ('35', 35), ('40', 40), ('45', 45), ('50', 50), ('55', 55), ('60', 60), ('65', 65), ('70', 70), ('75', 75), ('80', 80), ('85', 85), ('90', 90), ('95', 95), ('100', 100)])),
            ],
        ),
        migrations.CreateModel(
            name='VideoFrame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('columns', models.PositiveSmallIntegerField(help_text='Columns in a row cannot exceed 12')),
                ('url', models.URLField()),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kiosktv.Row')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Frame',
        ),
        migrations.AddField(
            model_name='carouselframe',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kiosktv.Row'),
        ),
    ]
